#! /usr/bin/env bash

readonly ERROR_SUDO=2

if [[ $(whoami) != "root" ]]; then
    runsudo;
fi

runsudo() {
    echo "mkvhost needs root access. Please run as sudo";
    exit $ERROR_SUDO
}

main() {
    ln -s $(pwd)/template.http /etc/apache2/sites-available/template.http
    ln -s $(pwd)/mkvhost /usr/local/bin/mkvhost

    chmod a+x $(pwd)/mkvhost
}

echo "Installing mkvhost."

main

echo "Installed links at:"
echo "/usr/local/bin/mkvhost"
echo "/etc/apache2/sites-available/template.http"
